### ISSUE TITLE
How to get the initial fake mask?

### ISSUE THREAD

**Issue by HalvesChen** [jiwei0921/DSU#1]
Hi, I want to train on custom dataset, but the code for the initial fake doesn't seem to be released here

**Comment by jiwei0921** [comment]
<img width="838" alt="image" src="https://github.com/jiwei0921/DSU/assets/32792115/07e55348-2e29-4707-8b35-3831d8361115">
Thanks for your interest in our work. We have provided the dataset used in paper for your reference.
